version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - restore_cache:
          name: Restoring dependencies
          keys:
            - dependencies-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Installing dependencies
          command: npm i
      - save_cache:
          name: Saving dependencies
          paths:
            - node_modules
          key: dependencies-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Building bundle
          command: npm run build
workflows:
  node-build:
    jobs:
      - build
